### ISSUE TITLE
Implement `permit` for metaTXz

### ISSUE THREAD

**Issue by Ro5s** [lexDAO/LexToken#3]
elegant implement 🔎 

https://github.com/ourzora/zora-contracts/blob/master/contracts/IToken.sol

**Comment by Ro5s** [comment]
Bounty 2 $LXK ⚔️

**Comment by Ro5s** [comment]
1 $LXK ⚔️ for describing way to get metaTXs out of current Gas Station Network `context` wrapper in LexToken ~~

**Comment by naszam** [comment]
Hi, 
You could use [OpenGSN](https://docs.opengsn.org/learn/index.html) by inheriting BaseRelayRecipient.sol into your contract, changing  msg.sender with _msgSender() and adding this function:
```
function _msgSender() internal override(Context, BaseRelayRecipient) view returns (address payable) {
            return BaseRelayRecipient._msgSender();
  }
```
to override context if inheriting from OpenZeppelin 

Hope that would help!

**Comment by Ro5s** [comment]
appreciate the feedback and instruction @naszam ~! We will try out the OpenGSN integration to start ~~

bounty awarded: https://etherscan.io/tx/0xa8ac62d3ced7eeeaeca43d0ffab317b3158809fa07f2570e49d06d7ffe4f74eb ⚔️
